"use client";

export interface RoadmapTask {
  title: string;
  assigned_to: string;
  milestone_marker: boolean;
}

export interface RoadmapPhase {
  name: string;
  description: string;
  order: number;
  tasks: RoadmapTask[];
}

export interface RoadmapData {
  version: number;
  phases: RoadmapPhase[];
}

interface Props {
  data: RoadmapData;
}

export default function RoadmapDashboard({ data }: Props) {
  
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      
      {/* Header Actions */}
      <div className="flex justify-between items-center bg-gray-800/50 backdrop-blur-md border border-gray-700 p-4 rounded-2xl shadow-xl">
        <div className="flex items-center gap-3">
          <span className="bg-cyan-900/30 text-cyan-400 px-3 py-1 rounded-full text-sm font-medium border border-cyan-500/30">
            Version {data.version}.0
          </span>
          <span className="text-gray-400 text-sm">Generated by NEXORA AI</span>
        </div>
        <button 
          onClick={handlePrint}
          className="text-sm font-medium text-white bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
          Export Professional Report
        </button>
      </div>

      {/* Timeline rendering */}
      <div className="space-y-8 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-gray-700 before:to-transparent">
        
        {data.phases?.map((phase: RoadmapPhase, idx: number) => (
          <div key={idx} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
            
            {/* Timeline Marker */}
            <div className="flex items-center justify-center w-10 h-10 rounded-full border-4 border-gray-900 bg-cyan-500 shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 z-10">
              <span className="text-gray-900 font-bold text-sm">{phase.order}</span>
            </div>
            
            {/* Content Card */}
            <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] p-4 rounded-xl border border-gray-700 bg-gray-800/80 shadow-xl backdrop-blur-sm transition-transform hover:-translate-y-1">
              <div className="flex flex-col mb-4">
                <h3 className="text-xl font-bold text-white mb-1">{phase.name}</h3>
                <p className="text-sm text-gray-400">{phase.description}</p>
              </div>
              
              <div className="space-y-3">
                {phase.tasks?.map((task: RoadmapTask, tidx: number) => (
                  <div key={tidx} className={`p-3 rounded-lg border ${task.milestone_marker ? 'bg-cyan-900/10 border-cyan-500/30' : 'bg-gray-900/50 border-gray-700'}`}>
                    <div className="flex justify-between items-start">
                      <p className="text-sm font-medium text-gray-200">
                        {task.milestone_marker && <span className="text-cyan-400 mr-2">★</span>}
                        {task.title}
                      </p>
                    </div>
                    <div className="mt-2 flex items-center justify-between">
                      <span className="text-xs bg-gray-800 text-gray-400 px-2 py-1 rounded">
                        Assignee: {task.assigned_to}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            
          </div>
        ))}

      </div>
    </div>
  );
}
